language: go
sudo: true
go:
 - 1.4
 - 1.5
 - 1.6
 - 1.7
 - tip
matrix:
 allow_failures:
   - go: tip
   - go: 1.4
   - go: 1.5
before_install:
 - sudo add-apt-repository -y ppa:kubuntu-ppa/backports
 - sudo add-apt-repository -y ppa:zoogie/sdl2-snapshots
 - sudo apt-get update
 - sudo apt-get install --force-yes libcv-dev libcvaux-dev libhighgui-dev libopencv-dev libsdl2-dev libsdl2-image-dev libsdl2 libusb-dev xvfb unzip libgtk2.0-0
 - cd $HOME/gopath/src/github.com/hybridgroup/gobot
 - go get github.com/axw/gocov/gocov
 - go get github.com/mattn/goveralls
 - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
install:
 - make deps
before_script:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
script:
 - ./ci/travis.sh
branches:
  except:
    - gobot.io
    - /^gobot-.*$/
